services:
  connector_nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

    container_name: connector_nginx
    volumes:
      - /app/backend/production-static:/app/backend/production-static
      - ../my_flashcards/my_flashcards_frontend/dist:/flashcard_dist
      - ../true-effects/trueeffectsfrontend/build:/build
      - ../trainer_page/trainer_page/dist:/trainer_dist
      - ../trainer_page/trainer_page/public:/public
      - ../web_grades_scrapper/web_grades_scrapper/dist:/scrapper_dist
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - connector
      - certificates

  production_certbot:
    image: certbot/certbot
    container_name: production_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./scripts:/scripts
    entrypoint: ["/scripts/run_certbot.sh"]
    networks:
      - certificates

networks:
  certificates:
  connector:
    external: true
