services:
  connector_nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

    container_name: connector_nginx
    volumes:
      - /app/backend/production-static:/app/backend/production-static
      - ../my_flashcards/my_flashcards_frontend/dist:/flashcard_dist
      - ../true-effects/trueeffectsfrontend/build:/build
      - ../trainer-backend/trainer_page/dist:/trainer_dist
      - ../trainer-backend/trainer_page/public:/public
      - ../web_grades_scrapper/web_grades_scrapper/dist:/scrapper_dist
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - connector
      - certificates

  production_certbot:
    image: certbot/certbot
    container_name: production_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./scripts:/scripts
    command: sh /scripts/run_certbot.sh
#    command: >
#      sh -c "
#        certbot certonly --webroot -w /var/www/certbot --force-renewal --email michal.lejwoda@gmail.com -d true-effects.pl --agree-tos &&
#        certbot certonly --webroot -w /var/www/certbot --force-renewal --email michal.lejwoda@gmail.com -d language-flashcards.pl --agree-tos &&
#        certbot certonly --webroot -w /var/www/certbot --force-renewal --email michal.lejwoda@gmail.com -d scrapper-omi.pl --agree-tos &&
#        certbot certonly --webroot -w /var/www/certbot --force-renewal --email michal.lejwoda@gmail.com -d trener-personalny-michal.pl --agree-tos
#      "
    networks:
      - certificates

networks:
  certificates:
  connector:
    external: true
