services:
  connector_nginx:
    image: nginx:latest
    container_name: connector_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../true-effects/certbot/conf:/etc/letsencrypt
      - ../true-effects/certbot/www:/var/www/certbot
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"
      - "443:443"
    networks:
      - connector
networks:
  connector:
    external: true

