volumes:
  production_django_static:
    external: true
  production_django_media:
    external: true
  production_trueeffects_static:
    external: true
  production_trueeffects_media:
    external: true
services:
  connector_nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: connector_nginx
    volumes:
      - production_django_static:/app/backend/production-static
      - production_django_media:/app/backend/production-media
      - production_trueeffects_static:/app/backend/production-trueeffects-static
      - production_trueeffects_media:/app/backend/production-trueeffects-media
      - ../my_flashcards/my_flashcards_frontend/dist:/flashcard_dist
      - ../true-effects/trueeffectsfrontend/build:/build
      - ../trainer_page/trainer_page/dist:/trainer_dist
      - ../trainer_page/trainer_page/public:/public
      - ../web_grades_scrapper/web_grades_scrapper/dist:/scrapper_dist
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - connector
      - certificates

  production_certbot:
    image: certbot/certbot
    container_name: production_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./scripts:/scripts
    entrypoint: ["/scripts/run_certbot.sh"]
    networks:
      - certificates

networks:
  certificates:
  connector:
    external: true
